### PR TITLE
Turkish language package creating.

### PR DESCRIPTION
**Pull request by bbilginn**

### CODE REVIEW

**Comment by PaulFreund** [comment]
Okay I submitted the package for certification and it should be available in the store in a few days :)

**Comment by bbilginn** [comment]
Good luck Paul!

**Comment by PaulFreund** [comment]
I looked today and the new version of Chat with turkish translation is now in the Store. Thank you for that!

**Comment by bbilginn** [comment]
Creating the first account "Auto away Message" stayed in English. I checked the source language. Do not have this text. Other than that, everything is visible properly. Thanks!

**Comment by PaulFreund** [comment]
Hello bbilginn, 
first sorry for not answering this, I simply forgot it, I'll fix this in the next version.

Second, are you still available for translation? The Microsoft store won't accept my new version because the turkish store page is not translated (last time they didn't care).

**Pull request merged**
