### PR TITLE
Clickable URLs in messages

### PR DESCRIPTION
**Pull request by zsgalusz**
Including a very simple workaround for the hyperlink position/size for now, with the sad side effect of hard to change font size.

### CODE REVIEW

**Comment by PaulFreund** [comment]
Again, big thank you! I'll try this out later today and file it as an update. I'll keep you updated here.

**Comment by PaulFreund** [comment]
I submitted the new version 1.2.0.35 to the store for certification. I changed the styling of the links a little bit so they better match the other links in the application and the text gets wrapped when the screen is too small. 
It also inspired me to add a few features while I'm at it, so now there is an option for spell-checking and one to auto-focus the text input when a conversation gets activated.

Thanks for your help! If you're still interested i'd be glad to see features like image preview coming from you :smile:
I'll notify you again when the new version hits the store.

**Comment by zsgalusz** [comment]
Thank you for the very quick update, already looking forward to using it on all my devices. The auto-focus was a great idea, it was on my list of things to look into too!
I will get started on the image previews in a few days, but before that I've got some family visits coming up. :smile:

**Comment by PaulFreund** [comment]
Unfortunately this will take a little longer as the reviewer roulette begins once more. This time they don't want to accept an untranslated Turkish store page (was english) which they had no problem accepting the last time, so now I first have to find somebody who can translate this for me. I'll kep ya updated

**Comment by zsgalusz** [comment]
Just giving a heads up, I am still planning to do the image previews, though I will take a bit longer than expected. My attention is currently distracted by some other personal projects, but I plan to get back to this soon.

**Comment by PaulFreund** [comment]
Thank you for the updated, I'm sorry I can't tell you anything new. I lack somebody for the turkish translation and I don't want to strip the language compeletely so I think I'll hire someone now, this takes to long this way

**Comment by PaulFreund** [comment]
I am pleased to say that the new version is now approved and should be in the store soon.

**Pull request merged**
